esphome:
  name: lilygo-eth-lite-esp32s3
  friendly_name: lilygo-eth-lite-esp32s3

esp32:
  board: esp32s3box
  framework:
    type: arduino

ethernet:
  type: W5500
  clk_pin: GPIO10
  mosi_pin: GPIO12
  miso_pin: GPIO11
  cs_pin: GPIO9
  interrupt_pin: GPIO13

# Enable logging
# logo out use usb see  -> https://esphome.io/components/logger.html
logger:
  level: DEBUG
  baud_rate: 115200
  logs:
    mqtt.component: DEBUG
    mqtt.client: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: "5IQaxyE4ynJ77XP4Oqz5nSYTEwx64h6d46+wadKuGlo="

    