esphome:
  name: lilygo-eth-elite
  friendly_name: lilygo-eth-elite

esp32:
  board: esp32s3box
  framework:
    type: arduino

ethernet:
  type: W5500
  clk_pin: GPIO48
  mosi_pin: GPIO21
  miso_pin: GPIO47
  cs_pin: GPIO45
  interrupt_pin: GPIO14

# Enable logging
logger:
  level: DEBUG
  baud_rate: 115200
  logs:
    mqtt.component: DEBUG
    mqtt.client: ERROR
    
# Enable Home Assistant API
api:
  encryption:
    key: "5IQaxyE4ynJ77XP4Oqz5nSYTEwx64h6d46+wadKuGlo="

    