name: Build-T-ETH-Lite-ESP32

on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - "examples/**"
      - "lib/**"
      - ".github/workflows/Build-T-ETH-Lite-ESP32.yml"
      - "platformio.ini"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        examples:
          - examples/UnitTestExample
          - examples/ETHOTA
          - examples/HelloServer
          - examples/SDWebServer
          - examples/MQTTClient
          - examples/ESPMQTTSClient
          - examples/StaticIPAddress
          - examples/UDPClientReceiver
          - examples/UDPClientSender
          - examples/UDPClientReceiverDirectPC
          - examples/UDPClientSenderDirectPC
          - examples/AsyncUDPServer
          - examples/AsyncUDPClient
          - examples/WebSocketClient
          - examples/WebSocketServer
          - examples/TCPClient
          - examples/TCPServer
          # - examples/RS485_Master
          # - examples/RS485_Slave
          # - examples/RS485_ModBUS
          - examples/TFT_ILI9341_Shield
          # - examples/CameraShield
          # - examples/LoRaShield
          # - examples/SPIExample
          - examples/SPI_Wire_DevicesExample
          # - examples/SharingSPIBus
          - examples/WireExample

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Run PlatformIO
        run: |
          export PLATFORMIO_SRC_DIR=${{ matrix.examples }}
          pio run -e  T-ETH-Lite-ESP32
